from ..core.base import PipelineStep
from ..core.models import PipelineState
from datetime import datetime


class MockTranscriptLoader(PipelineStep):
    """
    Injects a predefined transcript into the pipeline state.
    Used for testing downstream steps without needing audio files.
    """

    def execute(self, state: PipelineState) -> PipelineState:
        print(f"[{self.__class__.__name__}] Loading mock transcript...")

        # Get text from the config 'settings'
        mock_text = self.config.get("transcript_text", "")

        if not mock_text:
            print(f"[{self.__class__.__name__}] WARNING: No transcript_text provided in config!")

        state.transcript = mock_text
        # Simulate a timestamp usually generated by Whisper
        state.generated_at = datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

        return state